version: '3.8'

services:
  frontend:
    container_name: frontend
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    name: app-network
    driver: bridge